# Generated by Django 3.2.8 on 2021-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodupdate',
            name='journal_entry',
            field=models.CharField(max_length=1000),
        ),
    ]
