# Generated by Django 3.2.8 on 2021-10-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0002_alter_moodupdate_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodupdate',
            name='mood',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
