# Generated by Django 3.2.8 on 2021-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0003_moodupdate_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodupdate',
            name='user_id',
            field=models.CharField(default='test_user', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodupdate',
            name='mood',
            field=models.CharField(choices=[('H', 'Happy'), ('S', 'Sad'), ('A', 'Angry'), ('X', 'Anxious'), ('T', 'Stressed'), ('C', 'Confident'), ('O', 'Overwhelmed'), ('F', 'Fine')], max_length=1),
        ),
    ]
