# Generated by Django 3.2.8 on 2021-10-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0004_alter_moodupdate_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodupdate',
            name='user',
            field=models.CharField(default='past', max_length=150),
            preserve_default=False,
        ),
    ]
