# Generated by Django 3.2.8 on 2021-10-24 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodtracker', '0005_moodupdate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodupdate',
            name='user',
        ),
        migrations.AddField(
            model_name='moodupdate',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
